### ISSUE TITLE
Chromium 95 - Windows issues

### ISSUE THREAD

**Issue by shaunbellis** [madebymany/sir-trevor-js#589]
Since [Chromium 95 update](https://blog.chromium.org/2021/09/chrome-95-beta-secure-payment.html) we haven't been able to use Sir Trevor on any Windows based machines. It locks the browser window entirely when interacting with the block add button. Anyone else having this issue?

**Comment by raffij** [comment]
@shaunbellis which version are you using?

**Comment by shaunbellis** [comment]
Is it something you can help with @raffij ?

**Comment by shaunbellis** [comment]
It happens on the example too if that helps @raffij 
https://madebymany.github.io/sir-trevor-js/example.html

**Comment by NickGowdy** [comment]
@raffij We're also using sir-trevor and have noticed this defect very recently. On Chromium 95 when clicking on the textarea, it freezes up and I have to reload the page.

**Comment by raffij** [comment]
Yeah there's no console errors, some sort of loop.

Possibly it's the scribe library we use. Something which isn't maintained anymore.

I might have time this evening to take a look.

**Comment by raffij** [comment]
I've got a pr for the issue in the underlying library that is used.

It's a hack, but should allow usage again.

**Comment by olvado** [comment]
Thanks @raffij - I've merged the scribe PR and will look at putting together the relevant package releases tomorrow

**Comment by bigclumsyoaf** [comment]
Hi @raffij 

I've tried manually updating our version with this change. It's better, but I still see the problem occasionally. Can you give it another check? Using arrow keys to move around between lines, and then it just hangs.

**Comment by raffij** [comment]
I agree it's still an issue after further testing. It's also broken the way that we detect empty cells in some instances.

This appears to be a change in the way that contenteditable works in Chrome, I should test in a canary 96. As you'll have seen we use https://github.com/guardian/scribe to work with the editor, so we'll need to investigate further, but it's also difficult to debug. Which will take time.

**Comment by raffij** [comment]
Taken a look at future releases and from what I can tell 97 fixes the bug that is causing the issues.

Can someone else try Chrome Canary to see if it still has issues the the existing master?

**Comment by olvado** [comment]
I’ve downloaded the latest Chrome Canary and indeed the cpu issues do not appear to manifest!

**Comment by bigclumsyoaf** [comment]
Canary and Dev channels seem ok after quick tests. Beta still a problem. 

How long do fixes normally take to filter to stable?

**Comment by raffij** [comment]
They are saying Jan 4th. So need an interim solution probably.

**Comment by shaunbellis** [comment]
Thanks @raffij it would be awesome if you could.

**Comment by raffij** [comment]
@shaunbellis i don't have a solution available at the moment.

The hack I was able to deploy for the add button doesn't really work for cursor controls as you end up getting non functioning text inputs in places you don't expect.

It really feels like contenteditable has been broken for the way we use it until Chrome 97.

**Comment by shaunbellis** [comment]
> @shaunbellis i don't have a solution available at the moment.
> 
> The hack I was able to deploy for the add button doesn't really work for cursor controls as you end up getting non functioning text inputs in places you don't expect.
> 
> It really feels like contenteditable has been broken for the way we use it until Chrome 97.

Thank you for having a look. I'll close this issue with that. We will have to swap out the editior for another at least until #97.
